export default function generateDummy() {
  return {
    products: [
      {
        id: 'd2ba2dad-c018-4c2c-ac9b-b40d40576e90',
        // image: '/assets/cdr.jpg',
        image:
          'https://nrcqmmgoobssxyudfvxm.supabase.co/storage/v1/object/public/dnr-asset/product-image/CDR%20Sweet%20Orange%20Tab%20EFF%2015/DSC09644.jpg',
        name: 'CDR SWEET ORANGE TAB EFF 15',
        price: 50522,
        disc: 20,
        rating: 4.5,
        sold: 3400,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 'ea4f0c92-5639-4a2d-82ac-1a292cea5d4e',
        // image: '/assets/osteocare.jpg',
        image:
          'https://nrcqmmgoobssxyudfvxm.supabase.co/storage/v1/object/public/dnr-asset/product-image/Osteocare Sirup 100ml-btl/DSC09672.jpg',
        name: 'OSTEOCARE SIRUP100 ML-BTL',
        price: 60500,
        disc: 20,
        rating: 4.7,
        sold: 6400,
        category: 'beras',
        type: 'grosir',
      },
      {
        id: 'c49c0aac-fba3-4479-b544-b1dc1af7dfc3',
        // image: '/assets/redoxon.jpg',
        image:
          'https://nrcqmmgoobssxyudfvxm.supabase.co/storage/v1/object/public/dnr-asset/product-image/New%20Redoxon%20EFF%20Zinc%20Blackcurrant%20Tab%2010/DSC09612.jpg',
        name: 'NEW REDOXON EFF ZINC BLACKCURRANT TAB 10',
        price: 33956,
        disc: 10,
        rating: 4.7,
        sold: 4400,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 'a7315303-18be-4721-a52b-6dcab0071e68',
        // image: '/assets/jointace.jpg',
        image:
          'https://nrcqmmgoobssxyudfvxm.supabase.co/storage/v1/object/public/dnr-asset/product-image/Jointace%20Collagen%20Tablet/DSC09750.jpg',
        name: 'Jointace Collagen Tablet',
        price: 253000,
        disc: 5,
        rating: 4.7,
        sold: 1600,
        category: 'beras',
        type: 'retail',
      },
      {
        id: '04b379b6-4d9b-4dcb-a1e0-57ad77e97aa2',
        // image: '/assets/afitson.jpg',
        image:
          'https://nrcqmmgoobssxyudfvxm.supabase.co/storage/v1/object/public/dnr-asset/product-image/Afitson Balsem 18gr/DSC09875.jpg',
        name: 'Afitson Balsem 18 gr',
        price: 4700,
        disc: 8,
        rating: 4.8,
        sold: 2600,
        category: 'beras',
        type: 'grosir',
      },
      {
        id: 7,
        image: 'https://cf.shopee.co.id/file/d0b34adafaf40c05bf272971c9bc61cb_tn',
        name: 'KW Beras Merah - 1 Kg',
        price: 1800,
        disc: 20,
        rating: 1.5,
        sold: 1400,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 8,
        image: 'https://cf.shopee.co.id/file/d0b34adafaf40c05bf272971c9bc61cb_tn',
        name: 'KW Beras Merah - 1 Kg',
        price: 5000,
        disc: 10,
        rating: 1.7,
        sold: 1400,
        category: 'beras',
        type: 'grosir',
      },
      {
        id: 9,
        image: 'https://cf.shopee.co.id/file/1f6adb51c837d7ce97713df467d47d2f_tn',
        name: 'KW Beras Hitam - 5 Kg',
        price: 15000,
        disc: 1,
        rating: 1.7,
        sold: 1400,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 10,
        image: 'https://cf.shopee.co.id/file/93d2f506a1b427c96b8b6ba5e33ec37a_tn',
        name: 'KW Beras Melati - 5 Kg',
        price: 18000,
        disc: 1,
        rating: 1.7,
        sold: 600,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 11,
        image: 'https://cf.shopee.co.id/file/93d2f506a1b427c96b8b6ba5e33ec37a_tn',
        name: 'KW Beras Melati - 5 Kg',
        price: 18000,
        disc: 8,
        rating: 4.8,
        sold: 1600,
        category: 'beras',
        type: 'grosir',
      },
      {
        id: 12,
        image: 'https://cf.shopee.co.id/file/d0b34adafaf40c05bf272971c9bc61cb_tn',
        name: 'Beras Merah - 1 Kg',
        price: 18000,
        disc: 20,
        rating: 4.5,
        sold: 3400,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 13,
        image: 'https://cf.shopee.co.id/file/d0b34adafaf40c05bf272971c9bc61cb_tn',
        name: 'Beras Merah - 1 Kg',
        price: 15000,
        disc: 20,
        rating: 4.7,
        sold: 6400,
        category: 'beras',
        type: 'grosir',
      },
      {
        id: 14,
        image: 'https://cf.shopee.co.id/file/1f6adb51c837d7ce97713df467d47d2f_tn',
        name: 'Beras Hitam - 5 Kg',
        price: 25000,
        disc: 10,
        rating: 4.7,
        sold: 4400,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 15,
        image: 'https://cf.shopee.co.id/file/93d2f506a1b427c96b8b6ba5e33ec37a_tn',
        name: 'Beras Melati - 5 Kg',
        price: 58000,
        disc: 5,
        rating: 4.7,
        sold: 1600,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 16,
        image: 'https://cf.shopee.co.id/file/93d2f506a1b427c96b8b6ba5e33ec37a_tn',
        name: 'Beras Melati - 5 Kg',
        price: 48000,
        disc: 8,
        rating: 4.8,
        sold: 2600,
        category: 'beras',
        type: 'grosir',
      },
      {
        id: 17,
        image: 'https://cf.shopee.co.id/file/d0b34adafaf40c05bf272971c9bc61cb_tn',
        name: 'KW Beras Merah - 1 Kg',
        price: 1800,
        disc: 20,
        rating: 1.5,
        sold: 1400,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 18,
        image: 'https://cf.shopee.co.id/file/d0b34adafaf40c05bf272971c9bc61cb_tn',
        name: 'KW Beras Merah - 1 Kg',
        price: 5000,
        disc: 10,
        rating: 1.7,
        sold: 1400,
        category: 'beras',
        type: 'grosir',
      },
      {
        id: 19,
        image: 'https://cf.shopee.co.id/file/1f6adb51c837d7ce97713df467d47d2f_tn',
        name: 'KW Beras Hitam - 5 Kg',
        price: 15000,
        disc: 1,
        rating: 1.7,
        sold: 1400,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 20,
        image: 'https://cf.shopee.co.id/file/93d2f506a1b427c96b8b6ba5e33ec37a_tn',
        name: 'KW Beras Melati - 5 Kg',
        price: 18000,
        disc: 1,
        rating: 1.7,
        sold: 600,
        category: 'beras',
        type: 'retail',
      },
      {
        id: 21,
        image: 'https://cf.shopee.co.id/file/93d2f506a1b427c96b8b6ba5e33ec37a_tn',
        name: 'KW Beras Melati - 5 Kg',
        price: 18000,
        disc: 8,
        rating: 4.8,
        sold: 1600,
        category: 'beras',
        type: 'grosir',
      },
    ],
    categories: [
      {
        id: 1,
        name: 'Produk Konsumer',
        url: '/categories/Produk_Konsumer',
        icon: '/assets/food.svg',
      },
      {
        id: 2,
        name: 'Obat dan Multivitamin',
        url: '/categories/Obat_dan_Multivitamin',
        icon: '/assets/over_the_counter.svg',
      },
      {
        id: 3,
        name: 'Alat-alat Kesehatan',
        url: '/categories/Alat-alat_Kesehatan',
        icon: '/assets/medical.svg',
      },
      {
        id: 4,
        name: 'Produk Kecantikan',
        url: '/categories/Produk_Kecantikan',
        icon: '/assets/beauty.svg',
      },
      // {
      //   id: 4,
      //   name: 'Over The Counter',
      //   url: '/categories/over-the-counter',
      //   icon: '/assets/over_the_counter.svg',
      // },
      // {
      //   id: 5,
      //   name: 'Ethical',
      //   url: '/categories/ethical',
      //   icon: '/assets/ethical.svg',
      // },
      // {
      //   id: 6,
      //   name: 'Customer Health',
      //   url: '/categories/customer-health',
      //   icon: '/assets/consumer_health.svg',
      // },
      // {
      //   id: 7,
      //   name: 'Medicine',
      //   url: '/categories/medicine',
      //   icon: '/assets/medicine.svg',
      // },
      {
        id: 8,
        name: 'Produk Lainnya',
        url: '/categories/produk_lainnya',
        icon: '/assets/other.svg',
      },
    ],
  }
}
