export {default as UserDetail} from './account/UserDetail'
export {default as OutletDetail} from './account/OutletDetail'
export {default as OutletLicense} from './account/OutletLicense'
export {default as AddressDetail} from './account/AddressDetail'
export {default as AccountDetail} from './account/AccountDetail'
export {default as AddCustomerIdModal} from './account/AddCustomerIdModal'
export {default as OrderDetail} from './transaction/OrderDetail'

export {OrderStatus, ReturStatus, BackendOrderStatus} from './utils/orderStatus'
export {default as Sidebar} from './Sidebar'
export {default as OrderTrackingModal} from './transaction/OrderTrackingModal'
export {default as AddReviewModal} from './transaction/AddReviewModal'
export {default as ConfirmDeliveryModal} from './transaction/ConfirmDeliveryModal'
export {default as ReturCard} from './transaction/ReturCard'
export {default as ReturStats} from './utils/ReturStats'
export {default as ProductInfo} from './utils/ProductInfo'
export {SmallInformation, ExtraSmallInformation} from './utils/Information'
